<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            // CPU - 8 products
            [
                'name' => 'AMD Ryzen 7 7800X3D',
                'price' => 19995,
                'stock_count' => 15,
                'category' => 'CPU',
                'image_url' => '/images/products/cpu-1.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'Intel Core i9-14900K',
                'price' => 32500,
                'stock_count' => 8,
                'category' => 'CPU',
                'image_url' => '/images/products/cpu-2.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'AMD Ryzen 5 7600X',
                'price' => 12995,
                'stock_count' => 20,
                'category' => 'CPU',
                'image_url' => '/images/products/cpu-1.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'Intel Core i7-14700K',
                'price' => 24995,
                'stock_count' => 12,
                'category' => 'CPU',
                'image_url' => '/images/products/cpu-2.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'AMD Ryzen 9 7950X3D',
                'price' => 37995,
                'stock_count' => 5,
                'category' => 'CPU',
                'image_url' => '/images/products/cpu-1.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'Intel Core i5-14600K',
                'price' => 18995,
                'stock_count' => 18,
                'category' => 'CPU',
                'image_url' => '/images/products/cpu-2.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'AMD Ryzen 5 5600X',
                'price' => 8995,
                'stock_count' => 25,
                'category' => 'CPU',
                'image_url' => '/images/products/cpu-1.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'Intel Core i3-14100',
                'price' => 5995,
                'stock_count' => 30,
                'category' => 'CPU',
                'image_url' => '/images/products/cpu-2.jpg',
                'is_preorder' => false,
            ],

            // GPU - 8 products
            [
                'name' => 'ASUS ROG Strix GeForce RTX 4090',
                'price' => 148000,
                'stock_count' => 3,
                'category' => 'GPU',
                'image_url' => '/images/products/gpu.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'NVIDIA GeForce RTX 4080 Super',
                'price' => 89995,
                'stock_count' => 6,
                'category' => 'GPU',
                'image_url' => '/images/products/gpu.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'AMD Radeon RX 7900 XTX',
                'price' => 69995,
                'stock_count' => 5,
                'category' => 'GPU',
                'image_url' => '/images/products/gpu.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'ASUS TUF Gaming GeForce RTX 4070 Ti',
                'price' => 54995,
                'stock_count' => 10,
                'category' => 'GPU',
                'image_url' => '/images/products/gpu.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'Gigabyte GeForce RTX 4070 Super',
                'price' => 42995,
                'stock_count' => 12,
                'category' => 'GPU',
                'image_url' => '/images/products/gpu.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'AMD Radeon RX 7800 XT',
                'price' => 39995,
                'stock_count' => 8,
                'category' => 'GPU',
                'image_url' => '/images/products/gpu.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'ASUS Dual GeForce RTX 4060 Ti',
                'price' => 24995,
                'stock_count' => 15,
                'category' => 'GPU',
                'image_url' => '/images/products/gpu.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'Intel Arc A770 Limited',
                'price' => 19995,
                'stock_count' => 7,
                'category' => 'GPU',
                'image_url' => '/images/products/gpu.jpg',
                'is_preorder' => false,
            ],

            // Motherboard - 8 products
            [
                'name' => 'ASUS ROG Maximus Z790 Dark Hero',
                'price' => 41495,
                'stock_count' => 5,
                'category' => 'Motherboard',
                'image_url' => '/images/products/motherboard.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'MSI MEG Z790 ACE',
                'price' => 37995,
                'stock_count' => 4,
                'category' => 'Motherboard',
                'image_url' => '/images/products/motherboard.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'Gigabyte Z790 AORUS Master',
                'price' => 32995,
                'stock_count' => 7,
                'category' => 'Motherboard',
                'image_url' => '/images/products/motherboard.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'ASUS ROG Strix B650E-E Gaming WiFi',
                'price' => 22495,
                'stock_count' => 9,
                'category' => 'Motherboard',
                'image_url' => '/images/products/motherboard.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'MSI MAG B650 Tomahawk WiFi',
                'price' => 16995,
                'stock_count' => 11,
                'category' => 'Motherboard',
                'image_url' => '/images/products/motherboard.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'Gigabyte B650 Gaming X AX',
                'price' => 12995,
                'stock_count' => 14,
                'category' => 'Motherboard',
                'image_url' => '/images/products/motherboard.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'ASUS Prime Z790-A WiFi',
                'price' => 25995,
                'stock_count' => 8,
                'category' => 'Motherboard',
                'image_url' => '/images/products/motherboard.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'MSI MPG B550 Gaming Carbon WiFi',
                'price' => 11995,
                'stock_count' => 10,
                'category' => 'Motherboard',
                'image_url' => '/images/products/motherboard.jpg',
                'is_preorder' => false,
            ],

            // RAM - 8 products
            [
                'name' => 'Corsair Vengeance RGB DDR5 32GB (6000MHz)',
                'price' => 9895,
                'stock_count' => 25,
                'category' => 'RAM',
                'image_url' => '/images/products/ram.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'G.Skill Trident Z5 RGB DDR5 64GB',
                'price' => 18995,
                'stock_count' => 15,
                'category' => 'RAM',
                'image_url' => '/images/products/ram.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'Kingston Fury Beast DDR5 32GB (5600MHz)',
                'price' => 8495,
                'stock_count' => 30,
                'category' => 'RAM',
                'image_url' => '/images/products/ram.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'Corsair Dominator Platinum RGB DDR5 32GB',
                'price' => 12495,
                'stock_count' => 18,
                'category' => 'RAM',
                'image_url' => '/images/products/ram.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'G.Skill Trident Z5 Neo RGB 32GB (6000MHz)',
                'price' => 10995,
                'stock_count' => 20,
                'category' => 'RAM',
                'image_url' => '/images/products/ram.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'Kingston Fury Beast RGB 64GB DDR5',
                'price' => 15995,
                'stock_count' => 12,
                'category' => 'RAM',
                'image_url' => '/images/products/ram.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'Corsair Vengeance DDR5 64GB (5200MHz)',
                'price' => 12995,
                'stock_count' => 16,
                'category' => 'RAM',
                'image_url' => '/images/products/ram.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'TeamGroup T-Force Delta RGB 32GB',
                'price' => 7995,
                'stock_count' => 22,
                'category' => 'RAM',
                'image_url' => '/images/products/ram.jpg',
                'is_preorder' => false,
            ],

            // SSD - 8 products
            [
                'name' => 'Samsung 990 Pro 2TB NVMe',
                'price' => 17990,
                'stock_count' => 40,
                'category' => 'SSD',
                'image_url' => '/images/products/ssd.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'WD Black SN850X 2TB NVMe',
                'price' => 15995,
                'stock_count' => 35,
                'category' => 'SSD',
                'image_url' => '/images/products/ssd.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'Crucial T700 2TB Gen5 NVMe',
                'price' => 24995,
                'stock_count' => 12,
                'category' => 'SSD',
                'image_url' => '/images/products/ssd.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'Samsung 970 EVO Plus 1TB NVMe',
                'price' => 7995,
                'stock_count' => 50,
                'category' => 'SSD',
                'image_url' => '/images/products/ssd.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'WD Black SN770 1TB NVMe',
                'price' => 5995,
                'stock_count' => 45,
                'category' => 'SSD',
                'image_url' => '/images/products/ssd.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'Crucial P3 Plus 2TB NVMe',
                'price' => 9995,
                'stock_count' => 28,
                'category' => 'SSD',
                'image_url' => '/images/products/ssd.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'Samsung 980 PRO 1TB NVMe',
                'price' => 7495,
                'stock_count' => 32,
                'category' => 'SSD',
                'image_url' => '/images/products/ssd.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'Kingston A400 480GB SSD',
                'price' => 2495,
                'stock_count' => 60,
                'category' => 'SSD',
                'image_url' => '/images/products/ssd.jpg',
                'is_preorder' => false,
            ],

            // Case - 8 products
            [
                'name' => 'Lian Li O11 Dynamic EVO (Black)',
                'price' => 10999,
                'stock_count' => 10,
                'category' => 'Case',
                'image_url' => '/images/products/case.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'NZXT H9 Flow',
                'price' => 11995,
                'stock_count' => 8,
                'category' => 'Case',
                'image_url' => '/images/products/case.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'Corsair 4000D Airflow',
                'price' => 7495,
                'stock_count' => 15,
                'category' => 'Case',
                'image_url' => '/images/products/case.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'be quiet! Dark Base Pro 900',
                'price' => 14495,
                'stock_count' => 6,
                'category' => 'Case',
                'image_url' => '/images/products/case.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'Lian Li O11 Dynamic EVO (White)',
                'price' => 11495,
                'stock_count' => 9,
                'category' => 'Case',
                'image_url' => '/images/products/case.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'NZXT H7 Flow',
                'price' => 8995,
                'stock_count' => 12,
                'category' => 'Case',
                'image_url' => '/images/products/case.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'Corsair iCUE 5000D Airflow',
                'price' => 9995,
                'stock_count' => 11,
                'category' => 'Case',
                'image_url' => '/images/products/case.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'Thermaltake V250 TG ARGB',
                'price' => 5995,
                'stock_count' => 18,
                'category' => 'Case',
                'image_url' => '/images/products/case.jpg',
                'is_preorder' => false,
            ],

            // PSU - 8 products
            [
                'name' => 'Corsair RM1000e 1000W 80+ Gold',
                'price' => 11235,
                'stock_count' => 12,
                'category' => 'PSU',
                'image_url' => '/images/products/psu.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'be quiet! Straight Power 12 1000W',
                'price' => 12995,
                'stock_count' => 8,
                'category' => 'PSU',
                'image_url' => '/images/products/psu.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'Corsair CX750M 750W 80+ Bronze',
                'price' => 5495,
                'stock_count' => 20,
                'category' => 'PSU',
                'image_url' => '/images/products/psu.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'Seasonic Vertex GX-850 850W',
                'price' => 8995,
                'stock_count' => 14,
                'category' => 'PSU',
                'image_url' => '/images/products/psu.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'Corsair RM850x 850W 80+ Gold',
                'price' => 7995,
                'stock_count' => 16,
                'category' => 'PSU',
                'image_url' => '/images/products/psu.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'be quiet! Dark Power 13 1000W',
                'price' => 15995,
                'stock_count' => 5,
                'category' => 'PSU',
                'image_url' => '/images/products/psu.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'Thermaltake Smart 700W 80+ White',
                'price' => 3495,
                'stock_count' => 25,
                'category' => 'PSU',
                'image_url' => '/images/products/psu.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'EVGA SuperNOVA 850 G7',
                'price' => 8495,
                'stock_count' => 10,
                'category' => 'PSU',
                'image_url' => '/images/products/psu.jpg',
                'is_preorder' => false,
            ],

            // Cooler - 8 products
            [
                'name' => 'NZXT Kraken Elite 360 RGB',
                'price' => 17295,
                'stock_count' => 7,
                'category' => 'Cooler',
                'image_url' => '/images/products/cooler.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'Corsair iCUE H150i Elite',
                'price' => 15995,
                'stock_count' => 9,
                'category' => 'Cooler',
                'image_url' => '/images/products/cooler.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'be quiet! Dark Rock Pro 5',
                'price' => 8995,
                'stock_count' => 11,
                'category' => 'Cooler',
                'image_url' => '/images/products/cooler.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'Noctua NH-D15',
                'price' => 10995,
                'stock_count' => 8,
                'category' => 'Cooler',
                'image_url' => '/images/products/cooler.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'NZXT Kraken X63 RGB',
                'price' => 11995,
                'stock_count' => 10,
                'category' => 'Cooler',
                'image_url' => '/images/products/cooler.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'Corsair iCUE H100i Elite CW',
                'price' => 12995,
                'stock_count' => 12,
                'category' => 'Cooler',
                'image_url' => '/images/products/cooler.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'Noctua NH-U12A',
                'price' => 7995,
                'stock_count' => 14,
                'category' => 'Cooler',
                'image_url' => '/images/products/cooler.jpg',
                'is_preorder' => false,
            ],
            [
                'name' => 'DeepCool AK400',
                'price' => 2495,
                'stock_count' => 30,
                'category' => 'Cooler',
                'image_url' => '/images/products/cooler.jpg',
                'is_preorder' => false,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
